### ISSUE TITLE
dyn minio::s3::sse::Sse needs to implement Send trait for thread safety

### ISSUE THREAD

**Issue by louis030195** [minio/minio-rs#66]
Hello,

I'm currently using your library in a multithreaded context and I've encountered an issue related to Rust's concurrency safety guarantees.

The error message I'm getting is:
```
dyn minio::s3::sse::Sse` cannot be shared between threads safely
the trait `Sync` is not implemented for `dyn minio::s3::sse::Sse`
required for `&dyn minio::s3::sse::Sse` to implement `Send`
```

This suggests that the `dyn minio::s3::sse::Sse` type does not implement the Sync trait, which means it can't be shared between threads safely.

I believe the solution to this issue would be to ensure that `dyn minio::s3::sse::Sse` implements the Send trait, allowing it to be safely sent between threads.

(or maybe it's not thread safe with no workaround?)

**Comment by juanscr** [comment]
Hello there... Although I'm not a direct maintainer from this project, my team has created a pull request (https://github.com/minio/minio-rs/pull/60) that fixes this so it can be used safely in a concurrent environment; you can use our current fork for now as it has worked perfectly for us in our `axum` backend. If it works, you can upvote or comment in the PR so it may be approved.

The problem specifically is that functions use dynamic dispatch instead of generic functions, so it cannot guarantee that the send trait is implemented if it is.
